services:
  - type: web
    name: movie-listing-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/MovieListingBackend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080 